# Generated by Django 3.2.4 on 2021-12-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=2550)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
